#!/bin/bash
SCRIPT_FILE=$(readlink -f ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${SCRIPT_FILE})

# Bash mods always init 
source "${HOME}/.armystice/mod/mod-bash/init"

# todo: FIX! ln -s "${ARMYSTICE_MOD_HOME}/armystice-conf" > "${ARMYSTICE_SHORTCUTS_DIR}/conf"
